[package]
name = "paydao-proof"
version = "0.1.0"
description = "PayDAO MagicBlock Ephemeral Rollup proof"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "paydao_proof"

[features]
default = []

idl-build = [
    "anchor-lang/idl-build",
    "ephemeral-rollups-sdk/anchor"
]

no-entrypoint = []
no-idl = []
no-log-ix-name = []

init-if-needed = [
    "anchor-lang/init-if-needed"
]

cpi = [
    "no-entrypoint"
]

[dependencies]
anchor-lang = { version = "1.0.0", features = ["init-if-needed"] }
ephemeral-rollups-sdk = { version = "0.17.0", features = ["anchor"] }
